# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f98c229e7a61dfd427ca6ab91dc79b00a35a84576f19e091b42d180d08bf6b5973ae2c84e4d681dc7f4317145ce012a2f830c410d4540e9d46e58c74c2b3835

test:
  secret_key_base: 8ac3f5cc89eb0290ef8b7e63b129608661a9d417628842c0e7b077f7a775ff77b3b1be956abfa15e2e07803fd487fa7d2561825d96ab191a26cc239a08778f8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7f3349a2d8f4f5fc789c0f7fef5cc2b736366efc5fe36e0f378e4ac6ae03e4ebebe9d0043a907cf908e9ba585f8ea1ebd6c3d48a2c3204590f6e43a674bc5e0c
